// --- Data Definitions ---
// Auto-generated by tools/generator.py

const conversionTables = {
    englishR:  { max: 100, points: [[100, 68.0], [80, 58.7], [60, 49.4], [40, 40.1], [20, 30.8], [0, 20.0]] },
    englishL:  { max: 100, points: [[100, 77.5], [80, 65.0], [60, 52.4], [40, 39.8], [20, 27.2], [0, 20.0]] },
    math1A:    { max: 100, points: [[100, 78.6], [80, 68.7], [60, 58.7], [40, 48.0], [20, 38.0], [0, 28.0]] },
    math2BC:   { max: 100, points: [[100, 68.5], [80, 59.4], [60, 50.3], [40, 41.1], [20, 32.0], [0, 22.0]] },
    japanese:  { max: 200, points: [[200, 79.9], [150, 63.2], [100, 46.6], [80, 39.9], [50, 29.9], [0, 20.0]] },
    jp_modern: { max: 110, points: [[110, 74.6], [90, 62.7], [70, 50.8], [50, 38.9], [30, 27.0], [10, 15.1]] },
    jp_ancient:{ max: 45, points: [[45, 72.0], [35, 62.3], [25, 52.6], [15, 42.9], [5, 30.0]] },
    jp_kanbun: { max: 45, points: [[45, 71.0], [35, 62.8], [25, 54.7], [15, 46.6], [5, 38.0]] },
    science:   { max: 100, points: [[100, 72.0], [80, 64.0], [60, 56.0], [40, 48.0], [20, 40.0], [0, 30.0]] },
    social:    { max: 100, points: [[100, 73.8], [80, 62.9], [60, 52.1], [40, 41.2], [20, 30.0], [0, 20.0]] },
    info:      { max: 100, points: [[100, 81.2], [80, 67.2], [60, 53.2], [40, 39.2], [20, 25.2], [0, 15.0]] }
};

const subjectMaster = {
    englishR: { name: '英語(R)', max: 100, table: 'englishR' },
    englishL: { name: '英語(L)', max: 100, table: 'englishL' },
    math1A:   { name: '数学I・A', max: 100, table: 'math1A' },
    math2BC:  { name: '数学II・B・C', max: 100, table: 'math2BC' },
    jp_modern: { name: '現代文', max: 110, table: 'jp_modern', isSub: true },
    jp_ancient:{ name: '古文', max: 45, table: 'jp_ancient', isSub: true },
    jp_kanbun: { name: '漢文', max: 45, table: 'jp_kanbun', isSub: true },
    info:     { name: '情報', max: 100, table: 'info' },
    science1: { name: '理科①', max: 100, table: 'science' },
    science2: { name: '理科②', max: 100, table: 'science' },
    social:   { name: '地歴公民', max: 100, table: 'social' },
    social1:  { name: '地歴公民①', max: 100, table: 'social' },
    social2:  { name: '地歴公民②', max: 100, table: 'social' },
    scienceBasic: { name: '理科基礎', max: 100, table: 'science' }
};

const universities = [];